/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tiralabra;
import tiralabra.ui.Kayttoliittyma;

public class App {
    Kayttoliittyma kl = new Kayttoliittyma();

    public static void main(String[] args) {
        kl.kaynnista();
    }
}
